# Generated by Django 6.1.1 on 2026-09-21 07:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_advance_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cgst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Central GST (2.5% for 5% goods within UP).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_gstin",
            field=models.CharField(
                blank=True,
                help_text="Purchaser GSTIN (if registered dealer/firm).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="igst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Integrated GST (5.0% for interstate supply).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_date",
            field=models.DateField(
                blank=True,
                help_text="Official invoice date printed on bill.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Official sequential Tax Invoice number (e.g. MU/26-27/0081).",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_interstate",
            field=models.BooleanField(
                default=False,
                help_text="True if delivery is outside UP (IGST applicable), False for intra-UP (CGST+SGST).",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="place_of_supply",
            field=models.CharField(
                blank=True,
                help_text="State / jurisdiction of supply (e.g. Uttar Pradesh (09)).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="sgst_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="State GST (2.5% for 5% goods within UP).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="taxable_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total value before taxes.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="transport_mode",
            field=models.CharField(
                blank=True,
                default="Road",
                help_text="Mode of transport (e.g. Road, Courier, Tempo).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vehicle_number",
            field=models.CharField(
                blank=True, help_text="Vehicle Reg No or LR Tracking No.", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cgst_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Applicable GST rate (%)",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="hsn_code",
            field=models.CharField(
                blank=True, default="0910", help_text="4-digit HSN code", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="igst_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sgst_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="taxable_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Taxable amount for this line",
                max_digits=10,
            ),
        ),
    ]
