# Generated by Django 6.1.1 on 2026-09-23 20:33

import apps.core.validators
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[
                    apps.core.validators.FileSizeValidator(max_mb=10),
                    apps.core.validators.ImageTypeValidator(),
                ],
            ),
        ),
    ]
