# Generated by Django 6.1.1 on 2026-09-16 05:06

import apps.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomizeComboRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Build Your Own Combo", max_length=100),
                ),
                (
                    "required_item_count",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Number of products the customer must select to complete the combo.",
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=899,
                        help_text="Fixed price charged for a completed combo — regardless of which products are picked.",
                        max_digits=10,
                    ),
                ),
                (
                    "eligible_mode",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (all products at or under price cap)"),
                            ("manual", "Manual (hand-picked list below)"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "price_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="(Auto mode only) Include all products priced at or below this amount.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Build-Your-Own Combo Rule",
            },
        ),
        migrations.CreateModel(
            name="FixedCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text="Recommended: 1200×1200 px, JPG/WebP. Auto-resized on upload.",
                        null=True,
                        upload_to="combos/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("combo_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("meta_title", models.CharField(blank=True, max_length=160)),
                ("meta_description", models.TextField(blank=True, max_length=320)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomComboSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selected_products",
                    models.ManyToManyField(blank=True, to="catalog.product"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="combos.customizecomborule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomizeComboEligibleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligible_products",
                        to="combos.customizecomborule",
                    ),
                ),
            ],
            options={
                "unique_together": {("rule", "product")},
            },
        ),
        migrations.CreateModel(
            name="FixedComboItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="combos.fixedcombo",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combo_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("combo", "product")},
            },
        ),
    ]
