# Generated by Django 6.1.1 on 2026-09-16 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("combos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customcomboselection",
            name="combo_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customcomboselection",
            name="free_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="customcomboselection",
            name="savings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customizecomborule",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customizecomborule",
            name="display_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="customizecomborule",
            name="free_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Bonus product given completely FREE when the customer selects the required items.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="customizecomborule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("fixed_price", "Fixed Price (e.g. 10 for ₹999)"),
                    (
                        "buy_n_get_free",
                        "Buy N Get 1 Free (e.g. 5 Masalas + Free All-In-One)",
                    ),
                ],
                default="fixed_price",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customizecomborule",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customizecomborule",
            name="fixed_price",
            field=models.DecimalField(
                decimal_places=2,
                default=999,
                help_text="Fixed price charged for a completed combo (used when rule_type is Fixed Price).",
                max_digits=10,
            ),
        ),
    ]
