# Generated by Django 6.1.1 on 2026-09-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combos", "0002_customcomboselection_combo_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customcomboselection",
            name="items_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapping of product_id to selected quantity, e.g. {'13': 2, '12': 1}.",
            ),
        ),
        migrations.AddField(
            model_name="customizecomborule",
            name="max_units_per_product",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Maximum quantity of any single product allowed in this combo box (e.g. max 2 of the same masala).",
            ),
        ),
    ]
