# Generated by Django 6.1.1 on 2026-09-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combos", "0003_customcomboselection_items_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedcombo",
            name="is_featured_on_homepage",
            field=models.BooleanField(
                default=False,
                help_text="Show this combo in the Featured Spotlight on the homepage. (Only 1 combo will be featured on the homepage; all others appear under 'More Combos').",
            ),
        ),
    ]
