# Generated by Django 6.1.1 on 2026-09-16 05:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(default="MU Magic Masala", max_length=120),
                ),
                ("support_phone", models.CharField(blank=True, max_length=20)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Include country code, e.g. +919876543210",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("199.00"),
                        help_text="Checkout is blocked below this amount. Customer sees the shortfall.",
                        max_digits=10,
                    ),
                ),
                (
                    "cod_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("59.00"),
                        help_text="Extra fee added to the order total when customer selects Cash on Delivery.",
                        max_digits=10,
                    ),
                ),
                (
                    "cod_advance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Percentage of the order the customer pays online upfront when choosing COD (0–100).",
                        max_digits=5,
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank to disable free shipping. When set, orders above this amount ship free.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fixed_combo_item_count",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Number of items in a fixed (pre-built) combo.",
                    ),
                ),
                (
                    "customize_combo_item_count",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Number of items a customer must pick to complete a Build-Your-Own combo.",
                    ),
                ),
                (
                    "customize_combo_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("899.00"),
                        help_text="Fixed price charged for a completed Build-Your-Own combo.",
                        max_digits=10,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="MU Magic Masala — Fresh Spices, Delivered",
                        help_text="Used on pages that haven't set their own title.",
                        max_length=160,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Site-wide default meta description (used on pages without one).",
                        max_length=320,
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Default Open Graph image for social sharing. 1200×630 px, JPG/WebP, under 200KB.",
                        null=True,
                        upload_to="seo/",
                    ),
                ),
                ("fssai_license_number", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Site Settings",
            },
        ),
    ]
