# Generated by Django 6.1.1 on 2026-09-16 05:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_bar_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_bar_link",
            field=models.CharField(blank=True, default="/combos/", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_bar_text",
            field=models.CharField(
                blank=True,
                default="AUTHENTIC INDIAN MASALAS • FREE SHIPPING ABOVE ₹499",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cod_advance_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("59.00"),
                help_text="Fixed upfront advance payment collected online when choosing COD.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cod_advance_mode",
            field=models.CharField(
                choices=[("fixed", "Fixed Amount"), ("percent", "Percentage")],
                default="fixed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="brand_name",
            field=models.CharField(default="MAGIC MASALA", max_length=120),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="cod_advance_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Percentage of order customer pays upfront if percent mode is selected (0–100).",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="cod_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Extra delivery fee added to the order total when customer selects Cash on Delivery.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="customize_combo_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("999.00"),
                help_text="Fixed price charged for a completed Build-Your-Own 10-masala combo.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="free_shipping_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("499.00"),
                help_text="Leave blank to disable free shipping. When set, orders above this amount ship free.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="MAGIC MASALA — Premium authentic Indian masalas and spices stone-ground fresh. Richer aroma and unforgettable flavour in every meal.",
                help_text="Site-wide default meta description (used on pages without one).",
                max_length=320,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_title",
            field=models.CharField(
                default="MAGIC MASALA — Authentic Indian Spices, Delivered",
                help_text="Used on pages that haven't set their own title.",
                max_length=160,
            ),
        ),
    ]
