# Generated by Django 6.1.1 on 2026-09-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_announcement_bar_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="customize_combo_max_units_per_product",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Maximum quantity of any single product allowed in the Build-Your-Own combo.",
            ),
        ),
    ]
