# Generated by Django 6.1.1 on 2026-09-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_customize_combo_max_units_per_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bank_account_no",
            field=models.CharField(
                blank=True,
                default="27270200000665",
                help_text="Bank Account Number printed on invoices.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_ifsc_code",
            field=models.CharField(
                blank=True,
                default="BARB0BLYKNJ",
                help_text="Bank IFSC code for electronic settlements.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_name",
            field=models.CharField(
                blank=True,
                default="BANK OF BARODA, KASGANJ",
                help_text="Bank and branch name for NEFT/RTGS/IMPS customer payments.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="dispute_jurisdiction",
            field=models.CharField(
                default="KASGANJ",
                help_text="Jurisdiction town for legal dispute clause (e.g. KASGANJ).",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="firm_subtitle",
            field=models.CharField(
                blank=True,
                default="Wholesale & Retail : Kirana & Spice Manufacturers",
                help_text="Business description line printed below firm name on invoice.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="gstin",
            field=models.CharField(
                blank=True,
                default="09ALVPP8219Q1ZW",
                help_text="15-digit Goods and Services Tax Identification Number (State Code 09 = UP).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="invoice_phone",
            field=models.CharField(
                blank=True,
                default="7805105024",
                help_text="Contact number printed on invoices.",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="invoice_prefix",
            field=models.CharField(
                default="MU/26-27/",
                help_text="Series prefix for sequential Tax Invoices (e.g. MU/26-27/).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="legal_firm_name",
            field=models.CharField(
                default="Mahila Udhyog",
                help_text="Official registered business entity name printed on tax invoices.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="manufacturer_address",
            field=models.CharField(
                blank=True,
                default="Chitragupta Colony, Gali No.3, Kasganj- 207123",
                help_text="Registered manufacturing factory and office address.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="manufacturer_state",
            field=models.CharField(
                default="Uttar Pradesh",
                help_text="State of supplier (determines CGST+SGST vs IGST).",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="manufacturer_state_code",
            field=models.CharField(
                default="09",
                help_text="2-digit GST state code (09 for Uttar Pradesh).",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="next_invoice_number",
            field=models.PositiveIntegerField(
                default=81,
                help_text="Next sequential invoice serial number (as in bill book).",
            ),
        ),
    ]
