# Generated by Django 6.1.1 on 2026-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_bank_account_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal campaign name (e.g. 'Diwali 20% Off Mega Combo Blast')",
                        max_length=200,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject line that customers will see in their email inbox.",
                        max_length=255,
                    ),
                ),
                (
                    "preview_text",
                    models.CharField(
                        blank=True,
                        help_text="Teaser line shown in inbox snippet (e.g. 'Handcrafted spices at unbeatable festive prices.')",
                        max_length=255,
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        default="SPECIAL FESTIVE OFFER",
                        help_text="Highlight badge e.g. 'LIMITED TIME OFFER', 'NEW ARRIVAL', 'FESTIVAL SPECIAL'",
                        max_length=60,
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Bring Richer Aroma to Every Meal",
                        help_text="Main headline inside the email.",
                        max_length=200,
                    ),
                ),
                (
                    "subheading",
                    models.CharField(
                        blank=True,
                        default="Authentic stone-ground spices made with traditional recipes and zero preservatives.",
                        max_length=300,
                    ),
                ),
                (
                    "banner_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional header banner image URL (e.g. https://.../banner.jpg)",
                    ),
                ),
                (
                    "message_body",
                    models.TextField(
                        default="We are excited to bring you an exclusive discount on our best-selling fresh-ground Indian spices and custom combo boxes. Treat your family to unforgettable taste!",
                        help_text="Offer announcement message body. HTML paragraphs or plain text allowed.",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        help_text="Discount coupon code to display in prominent voucher badge (e.g. FESTIVE20).",
                        max_length=50,
                    ),
                ),
                (
                    "discount_highlight",
                    models.CharField(
                        blank=True,
                        default="FLAT 20% OFF",
                        help_text="e.g. 'FLAT 20% OFF', 'BUY 1 GET 1 FREE', 'EXTRA ₹100 OFF'",
                        max_length=60,
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="Explore Spice Combos Now",
                        help_text="Button text inside the email.",
                        max_length=60,
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        default="/combos/",
                        help_text="URL where the button takes customers (relative e.g. /combos/ or absolute).",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending in progress"),
                            ("sent", "Sent Successfully"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "recipients_sent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of customers who received this campaign.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Email Campaign & Offer",
                "verbose_name_plural": "Email Campaigns & Offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Registration"),
                            ("order_confirmation", "Order Confirmation"),
                            ("status_update", "Order Status Update"),
                            ("password_reset", "Password Reset Link"),
                            ("password_change", "Password Change Alert"),
                            ("campaign", "Offer / Marketing Campaign"),
                            ("test", "Brevo Connection Test"),
                            ("other", "Other Notification"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent Successfully"),
                            ("failed", "Delivery Failed"),
                        ],
                        default="sent",
                        max_length=15,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Email Delivery Log",
                "verbose_name_plural": "Email Delivery Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master toggle to enable or disable all outgoing emails.",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        default="smtp-relay.brevo.com",
                        help_text="SMTP Relay Host (e.g. smtp-relay.brevo.com)",
                        max_length=120,
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(
                        default=587, help_text="SMTP Port (587 for TLS, 465 for SSL)"
                    ),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(
                        default=True, help_text="Use TLS for secure email transport."
                    ),
                ),
                (
                    "smtp_user",
                    models.CharField(
                        default="care@mumagicmasala.com",
                        help_text="Brevo SMTP login / account email.",
                        max_length=150,
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        default="",
                        blank=True,
                        help_text="Brevo SMTP Key — set in admin panel.",
                        max_length=255,
                    ),
                ),

                (
                    "from_name",
                    models.CharField(
                        default="MU Magic Masala",
                        help_text="Sender display name seen in inbox.",
                        max_length=100,
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        default="care@mumagicmasala.com",
                        help_text="Sender email address.",
                        max_length=254,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="care@mumagicmasala.com",
                        help_text="Reply-to email for customer queries.",
                        max_length=254,
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True,
                        default="7805105024",
                        help_text="Support telephone / WhatsApp shown in email footers.",
                        max_length=25,
                    ),
                ),
                (
                    "welcome_email_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Send a branded welcome email with coupon when a new customer registers.",
                    ),
                ),
                (
                    "welcome_email_subject",
                    models.CharField(
                        default="Welcome to MU Magic Masala! 🌶️ Enjoy 10% Off Your First Order",
                        max_length=255,
                    ),
                ),
                (
                    "welcome_coupon_code",
                    models.CharField(
                        blank=True,
                        default="WELCOME10",
                        help_text="Special discount coupon code to highlight in welcome email.",
                        max_length=50,
                    ),
                ),
                (
                    "order_confirmation_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Send itemized order confirmation email immediately after payment/checkout.",
                    ),
                ),
                (
                    "order_confirmation_subject",
                    models.CharField(
                        default="Order Confirmed — #{order_number} | MU Magic Masala",
                        max_length=255,
                    ),
                ),
                (
                    "order_status_update_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Send tracking & delivery status update email when order status changes in admin.",
                    ),
                ),
                (
                    "order_status_subject",
                    models.CharField(
                        default="Order Update: #{order_number} is now {status_display} | MU Magic Masala",
                        max_length=255,
                    ),
                ),
                (
                    "password_change_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Send security confirmation email when customer updates their password.",
                    ),
                ),
                (
                    "password_change_subject",
                    models.CharField(
                        default="Security Alert: Your MU Magic Masala Password Was Changed",
                        max_length=255,
                    ),
                ),
                (
                    "abandoned_cart_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Send friendly reminders to customers who left items in their cart.",
                    ),
                ),
                (
                    "abandoned_cart_subject",
                    models.CharField(
                        default="You left something delicious behind! 🌶️ Complete your order at MU Magic Masala",
                        max_length=255,
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True,
                        default="Pure, cold stone-ground, preservative-free Indian spices straight from our mill to your kitchen.",
                        help_text="Custom brand message shown at the bottom of all emails.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Settings & Brevo",
                "verbose_name_plural": "Email Settings & Brevo",
            },
        ),
    ]
