# Generated by Django 6.1.1 on 2026-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_emailcampaign_emaillog_emailsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsettings",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Brevo SMTP Key (xsmtpsib-...) — set this in admin, never hardcode.",
                max_length=255,
            ),
        ),
    ]
