# Generated by Django 6.1.1 on 2026-09-16 05:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat (₹ off)"),
                            ("percent", "Percentage (% off)"),
                        ],
                        default="flat",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_discount_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount amount for percentage coupons. Leave blank for no cap.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "min_cart_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum order value for this coupon to be valid.",
                        max_digits=10,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "usage_limit_total",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum total uses. Leave blank for unlimited.",
                        null=True,
                    ),
                ),
                (
                    "usage_limit_per_customer",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum uses per customer. Leave blank for unlimited.",
                        null=True,
                    ),
                ),
                (
                    "first_order_only",
                    models.BooleanField(
                        default=False,
                        help_text="Only valid on a customer's first order.",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("all", "All Orders"),
                            ("products", "Specific Products"),
                            ("categories", "Specific Categories"),
                            ("combos", "Combos Only"),
                        ],
                        default="all",
                        max_length=15,
                    ),
                ),
                (
                    "show_on_announcement_bar",
                    models.BooleanField(
                        default=False,
                        help_text="Show this coupon code in the announcement bar.",
                    ),
                ),
                (
                    "applicable_categories",
                    models.ManyToManyField(blank=True, to="catalog.category"),
                ),
                (
                    "applicable_products",
                    models.ManyToManyField(blank=True, to="catalog.product"),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
    ]
