# Generated by Django 6.1.1 on 2026-09-20 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_couponusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Start date & time."
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiry date & time. Leave blank for no expiry.",
                null=True,
            ),
        ),
    ]
