"""
Populate actual products from user's price list, removing dummy products.
"""
import os
import sys
from decimal import Decimal

# Ensure utf-8 output on Windows console
if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.development')
django.setup()

from django.db import transaction
from apps.catalog.models import Category, Product, ProductVariant, Tag
from apps.cart.models import Cart, CartItem
from apps.combos.models import FixedCombo, FixedComboItem, CustomizeComboRule, CustomizeComboEligibleProduct, CustomComboSelection
from apps.reviews.models import ProductReview

print("Starting clean product population...")

# 1. Clean existing dummy data
with transaction.atomic():
    print("Clearing cart items, combo items, reviews, and old products...")
    CartItem.objects.all().delete()
    CustomComboSelection.objects.all().delete()
    FixedComboItem.objects.all().delete()
    FixedCombo.objects.all().delete()
    CustomizeComboEligibleProduct.objects.all().delete()
    ProductReview.objects.all().delete()
    ProductVariant.objects.all().delete()
    Product.objects.all().delete()
    Category.objects.all().delete()
    print("Old dummy data cleared successfully.")

# 2. Create Categories
categories_data = [
    {
        "name": "Daily Cooking & Pure Spices",
        "slug": "daily-cooking-pure-spices",
        "display_order": 1,
        "description": "<p>100% pure, stone-ground foundational spices and whole herbs for daily Indian cooking. Cold-milled to preserve natural essential oils, deep aroma, and authentic taste.</p>",
        "meta_title": "Pure Stone-Ground Spices & Daily Essentials | Authentic Indian Masalas",
        "meta_description": "Shop 100% pure stone-ground haldi, dhaniya, mirch, jeera, and everyday cooking spices. Zero adulteration, high essential oils."
    },
    {
        "name": "Ready Masala Blends",
        "slug": "ready-masala-blends",
        "display_order": 2,
        "description": "<p>Handcrafted master recipe blends for authentic regional curries, gravies, and restaurant-style dishes. No fillers, starches, or artificial colors.</p>",
        "meta_title": "Ready Masala Blends & Curry Powders | Authentic Regional Recipes",
        "meta_description": "Explore master blended Garam Masala, Kitchen King, Pav Bhaji, Chole, and Paneer masalas crafted from whole roasted spices."
    },
    {
        "name": "Herbs, Salts & Seasonings",
        "slug": "herbs-salts-seasonings",
        "display_order": 3,
        "description": "<p>Artisanal mineral salts, dehydrated gourmet powders, and global sprinkles that transform everyday snacks, pasta, salads, and street food.</p>",
        "meta_title": "Natural Salts, Herbs & Sprinkles | Himalayan Rock Salt, Peri Peri & Herbs",
        "meta_description": "Buy pure Sendha Namak, Kala Namak, Oregano, Chilli Flakes, Peri Peri, Garlic and Onion powders."
    },
    {
        "name": "Pure Hing (Asafoetida)",
        "slug": "pure-hing",
        "display_order": 4,
        "description": "<p>The golden crown of Indian tadka. Uncompromisingly potent raw and compounded Bandhani asafoetida with an intoxicating aroma and digestive goodness.</p>",
        "meta_title": "Pure Raw Hing & Bandhani Asafoetida | Intense Tadka Aroma",
        "meta_description": "Authentic Raw Hing crystals and Bandhani Asafoetida with superior aroma and purity. Essential for dals, curries, and pickles."
    },
    {
        "name": "Chaat, Drinks & Refreshers",
        "slug": "chaat-drinks-refreshers",
        "display_order": 5,
        "description": "<p>Digestive drink mixes, street-style chatpata masalas, and warming royal tea spices crafted to revive the senses and delight the palate.</p>",
        "meta_title": "Chaat Masalas, Jaljeera, Shikanji & Chai Masala | Royal Refreshers",
        "meta_description": "Street-style Chaat Masala, tangy Jaljeera, Shikanji, Pani Puri water blend, and fragrant immunity Chai Masala."
    },
    {
        "name": "Handcrafted Achaar (Pickles)",
        "slug": "handcrafted-achaar",
        "display_order": 6,
        "description": "<p>Traditional sun-cured Indian pickles prepared in cold-pressed kachi ghani mustard oil with coarse stone-ground spices and grandma's secret recipes.</p>",
        "meta_title": "Authentic Handcrafted Pickles | Aam, Mirch, Nimbu & Mix Achaar",
        "meta_description": "Sun-ripened homemade style Aam Ka Achaar, Stuffed Chilli Pickle, Lemon Pickle, and Mixed Pickles in 6-inch jars."
    }
]

created_categories = {}
for cat_info in categories_data:
    cat = Category.objects.create(
        name=cat_info["name"],
        slug=cat_info["slug"],
        display_order=cat_info["display_order"],
        description=cat_info["description"],
        meta_title=cat_info["meta_title"],
        meta_description=cat_info["meta_description"],
        is_active=True
    )
    created_categories[cat.slug] = cat
    print(f"Created category: {cat.name}")

# 3. Product Catalog definition from PDF
products_data = [
    # ── Herbs, Salts & Hing ──
    {
        "name": "Artisanal Dried Oregano",
        "slug": "artisanal-dried-oregano",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-HSH-OREG-100G",
        "weight_label": "100 gm",
        "price": Decimal("180.00"),
        "mrp": Decimal("210.00"),
        "short_description": "Sun-dried Mediterranean oregano leaves with robust herbal fragrance and earthy citrus warmth.",
        "description": "<p>Our Artisanal Dried Oregano is sourced from select herb farms and carefully shade-dried to retain volatile herbal oils. It delivers a pungent, savory aroma and slightly peppery sweetness that instantly elevates pizzas, pasta sauces, garlic bread, baked potatoes, and grilled marinades.</p>",
        "ingredients": "100% Pure Dried Mediterranean Oregano Leaves (Origanum vulgare).",
        "how_to_use": "Crush gently between palms to awaken aroma and sprinkle over hot pizzas, pastas, bruschetta, and salads.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Crushed Red Chilli Flakes",
        "slug": "crushed-red-chilli-flakes",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-HSH-CHLF-100G",
        "weight_label": "100 gm",
        "price": Decimal("180.00"),
        "mrp": Decimal("210.00"),
        "short_description": "Coarsely crushed fiery red chillies with golden seeds for genuine crunchy texture and sharp heat.",
        "description": "<p>Crafted from whole sun-cured dried red chillies, our Crushed Chilli Flakes provide the ideal balance of pungent heat and vibrant texture. Contains whole seeds for an authentic bite on Italian classics, savory snacks, omelettes, and noodles.</p>",
        "ingredients": "100% Sun-dried whole red chillies with seeds, coarsely crushed.",
        "how_to_use": "Sprinkle over pizzas, pastas, avocado toast, stir-fries, and dipping oils.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Zesty Peri Peri Seasoning",
        "slug": "zesty-peri-peri-seasoning",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-HSH-PERI-100G",
        "weight_label": "100 gm",
        "price": Decimal("120.00"),
        "mrp": Decimal("150.00"),
        "short_description": "Fiery African bird's eye chilli blend with tangy garlic, onion, and herb notes for snacks and fries.",
        "description": "<p>A high-voltage gourmet spice sprinkle combining fiery red chillies, dehydrated garlic, onion, savory black salt, and subtle citrus zest. Turns plain french fries, popcorn, crispy chicken, and paneer tikkas into cafe-style sensations.</p>",
        "ingredients": "African Bird's Eye Chilli, Garlic Powder, Onion Powder, Black Salt, Oregano, Citric Acid, Mixed Spices.",
        "how_to_use": "Toss generously over hot french fries, popcorn, wedges, roasted makhanas, and grilled sandwiches.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "Himalayan Pink Rock Salt (Sendha Namak)",
        "slug": "himalayan-pink-rock-salt-sendha-namak",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-HSH-RSALT-200G",
        "weight_label": "200 gm",
        "price": Decimal("60.00"),
        "mrp": Decimal("90.00"),
        "short_description": "100% pure unrefined mineral rock salt, rich in natural trace minerals and approved for fasting (vrat).",
        "description": "<p>Mined from pristine ancient salt deposits, this Himalayan Rock Salt (Sendha Namak) is unbleached and free from chemical anti-caking agents. Retains essential trace minerals that support electrolyte balance and gentle digestion. Approved for religious fasting and daily gourmet seasoning.</p>",
        "ingredients": "100% Pure Natural Himalayan Pink / Rock Salt crystals.",
        "how_to_use": "Use as a direct 1:1 replacement for processed table salt in all cooking, baking, fasting dishes, and seasoning.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Artisanal Black Salt (Kala Namak)",
        "slug": "artisanal-black-salt-kala-namak",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-HSH-BSALT-200G",
        "weight_label": "200 gm",
        "price": Decimal("60.00"),
        "mrp": Decimal("90.00"),
        "short_description": "Traditional volcanic sulfur-rich black salt stone-ground for distinctive savory aroma and digestive aid.",
        "description": "<p>An indispensable gem of Indian street food and Ayurvedic cuisine. Our Kala Namak is traditionally kiln-fired with Ayurvedic herbs and harad seeds, producing a characteristic umami sulfur profile that makes chaats, chutneys, raitas, and fruit salads mouthwateringly tangy.</p>",
        "ingredients": "100% Natural Himalayan Black Salt with indigenous botanical minerals.",
        "how_to_use": "Add a pinch to raita, curd, dahi bhalla, fruit chaat, lemonade, and digestive drinks.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Natural Mineral White Salt",
        "slug": "natural-mineral-white-salt",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-HSH-WSALT-200G",
        "weight_label": "200 gm",
        "price": Decimal("50.00"),
        "mrp": Decimal("80.00"),
        "short_description": "Pure solar-evaporated mineral white cooking salt without harsh bleaching or chemical additives.",
        "description": "<p>A clean, wholesome mineral white salt harvested through natural solar evaporation. Offers a pure, balanced salinity that enhances the natural flavors of curries, broths, and dough without the bitter metallic aftertaste of industrial bleached salt.</p>",
        "ingredients": "100% Natural Sea & Mineral White Cooking Salt.",
        "how_to_use": "Use in daily cooking, boiling vegetables, kneading dough, and seasoning soups.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Street-Style Panipuri Masala",
        "slug": "street-style-panipuri-masala",
        "category_slug": "chaat-drinks-refreshers",
        "sku": "MM-HSH-PANI-100G",
        "weight_label": "100 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "Crisp, tangy, and spicy pani puri water blend with fresh mint, cumin, amchoor, and rock salt.",
        "description": "<p>Recreate the unmistakable magic of India's favorite street treat at home. Formulated with cooling mint, roasted cumin, black salt, zesty amchoor, and subtle green chilli heat to prepare the ultimate refreshing teekha and khatta pani for crispy puris.</p>",
        "ingredients": "Mint, Coriander, Black Salt, Cumin, Dry Mango (Amchoor), Ginger, Green Chilli, Asafoetida, Citric Acid.",
        "how_to_use": "Dissolve 2-3 tablespoons in 1 liter of chilled water. Add fresh lemon juice, crushed ice, and boondi for instant pani puri water.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "Pure Dehydrated Onion Powder",
        "slug": "pure-dehydrated-onion-powder",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-HSH-ONION-100G",
        "weight_label": "100 gm",
        "price": Decimal("120.00"),
        "mrp": Decimal("150.00"),
        "short_description": "100% farm-fresh dehydrated onions ground into fine aromatic powder for rich gravies and dry rubs.",
        "description": "<p>Save prep time without compromising on authentic flavor. Made from premium white onions dehydrated at low temperatures and finely milled. Dissolves seamlessly into creamy gravies, marinades, dips, dressings, and seasoning blends without tears or frying.</p>",
        "ingredients": "100% Pure Dehydrated Ground Onion.",
        "how_to_use": "Add 1 tsp directly to curries, creamy sauces, barbecue rubs, or burger patties for rich savory depth.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Natural Spray-Dried Tomato Powder",
        "slug": "natural-spray-dried-tomato-powder",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-HSH-TOM-100G",
        "weight_label": "100 gm",
        "price": Decimal("30.00"),
        "mrp": Decimal("60.00"),
        "short_description": "Sun-ripened red tomatoes dried into concentrated tangy powder for instant curries and snacks.",
        "description": "<p>Concentrated essence of ripe, luscious red tomatoes with zero added starch, sugar, or artificial color. Perfect for enriching makhani gravies, seasoning popcorn, instant tomato soups, dips, and adding natural tang to dal and rice.</p>",
        "ingredients": "100% Pure Dehydrated Red Tomato Solids.",
        "how_to_use": "Stir into gravies for instant richness and color, or dust over roasted makhanas and popcorn.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Aromatic Garlic Powder",
        "slug": "aromatic-garlic-powder",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-HSH-GARL-100G",
        "weight_label": "100 gm",
        "price": Decimal("120.00"),
        "mrp": Decimal("150.00"),
        "short_description": "Intensely pungent dehydrated garlic cloves stone-ground into silky savory seasoning.",
        "description": "<p>Enjoy the robust, punchy flavor of freshly peeled garlic in a convenient, mess-free powder. Crafted from slow-dehydrated high-allicin garlic cloves that retain their natural savory sweetness and pungent kick. Ideal for garlic bread, pasta, pizza rubs, and curries.</p>",
        "ingredients": "100% Dehydrated Pure Garlic Cloves.",
        "how_to_use": "Blend into softened butter for instant garlic bread spread, or add 1/2 tsp to curries and stir-fries.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Royal Raw Hing (Pure Asafoetida)",
        "slug": "royal-raw-hing-pure-asafoetida",
        "category_slug": "pure-hing",
        "sku": "MM-HSH-RHING",
        "weight_label": "5 gm",
        "price": Decimal("210.00"),
        "mrp": Decimal("250.00"),
        "short_description": "Ultra-potent authentic raw crystal asafoetida resin. A microscopic pinch infuses deep culinary aroma.",
        "description": "<p>The gold standard of Indian culinary hing. Sourced from authentic Ferula resin, this Raw Hing is virtually unadulterated and extraordinarily potent. A single grain dissolved in hot ghee or oil releases an unforgettable sweet-savory allium aroma that elevates dals, kadhis, sambhars, and pickles.</p>",
        "ingredients": "Pure Compounded Raw Asafoetida Resin (Ferula foetida), Edible Acacia Gum.",
        "how_to_use": "Dissolve a matchhead-sized speck in hot ghee/oil at the start of tadka or in a spoonful of warm water before adding to curries.",
        "is_featured": True,
        "is_bestseller": True,
        "variants": [
            {"size_label": "5 gm", "price": Decimal("210.00"), "mrp": Decimal("250.00"), "sku": "MM-HSH-RHING-5G"},
            {"size_label": "10 gm", "price": Decimal("450.00"), "mrp": Decimal("480.00"), "sku": "MM-HSH-RHING-10G"}
        ]
    },
    {
        "name": "Special Bandhani Hing (Tadka Asafoetida)",
        "slug": "special-bandhani-hing-tadka-asafoetida",
        "category_slug": "pure-hing",
        "sku": "MM-HSH-BHING",
        "weight_label": "20 gm",
        "price": Decimal("100.00"),
        "mrp": Decimal("120.00"),
        "short_description": "Classic kitchen-friendly compounded hing formulated for everyday dal tadka, rasam, and curries.",
        "description": "<p>A heritage formulation favored across North and South Indian households for daily cooking. Blended smoothly with edible gum and wheat flour to release a gentle, balanced aroma without burning easily in high-heat tadka. Promotes gut health and easy digestion.</p>",
        "ingredients": "Compounded Asafoetida (Bandhani grade), Edible Wheat Flour, Gum Arabic.",
        "how_to_use": "Add a generous pinch (1/4 tsp) to hot oil or ghee with cumin and mustard seeds for authentic aroma.",
        "is_featured": False,
        "is_bestseller": False,
        "variants": [
            {"size_label": "20 gm", "price": Decimal("100.00"), "mrp": Decimal("120.00"), "sku": "MM-HSH-BHING-20G"},
            {"size_label": "50 gm", "price": Decimal("250.00"), "mrp": Decimal("280.00"), "sku": "MM-HSH-BHING-50G"}
        ]
    },

    # ── Ready Masala Mixes ──
    {
        "name": "Royal Kitchen King Masala",
        "slug": "royal-kitchen-king-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-KK-100G",
        "weight_label": "100 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "The versatile master curry blend of 14 whole spices that transforms simple vegetables into banquet curries.",
        "description": "<p>The undisputed king of the Indian spice shelf. Our Kitchen King blend unites coriander, cumin, turmeric, black pepper, nutmeg, mace, and green cardamom in perfect culinary harmony. Imparts a rich golden hue and complex restaurant-style aroma to paneer, mixed vegetables, koftas, and dry sabjis.</p>",
        "ingredients": "Coriander, Cumin, Turmeric, Black Pepper, Fenugreek, Mustard, Ginger, Green Cardamom, Nutmeg, Cinnamon, Mace, Cloves, Bay Leaf.",
        "how_to_use": "Add 1 to 1.5 teaspoons to onion-tomato masala base while frying until oil separates.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "Amritsari Channa Masala",
        "slug": "amritsari-channa-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-CHAN-100G",
        "weight_label": "100 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "Authentic Punjabi chole masala crafted with real dried pomegranate seeds (anardana) for dark tangy gravy.",
        "description": "<p>Recreate the iconic taste of Amritsari Pindi Chole at home. Ground with authentic wild anardana (pomegranate seeds), roasted cumin, black cardamom, and dried mango to achieve that signature dark, tangy, and piquant gravy beloved with bhaturas and kulchas.</p>",
        "ingredients": "Pomegranate Seeds (Anardana), Coriander, Cumin, Dry Mango, Black Pepper, Kashmiri Chilli, Cloves, Bay Leaf, Black Salt, Ginger.",
        "how_to_use": "Simmer 2 tsp with boiled chickpeas, onion-tomato gravy, and a splash of chickpea broth until thick and luscious.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "Chatpata Chaat Masala",
        "slug": "chatpata-chaat-masala",
        "category_slug": "chaat-drinks-refreshers",
        "sku": "MM-RMM-CHAAT-125G",
        "weight_label": "125 gm",
        "price": Decimal("120.00"),
        "mrp": Decimal("150.00"),
        "short_description": "Mouthwatering zesty sprinkle made with amchoor, black salt, and roasted cumin for snacks and street food.",
        "description": "<p>A high-impact chatpata sprinkle that delivers the authentic tang of Delhi street chaat. Prepared with sun-dried raw mango powder, mineral-dense black salt, freshly roasted cumin seeds, and digestive hing. Guaranteed to awaken salads, pakoras, fruits, and papdi chaat.</p>",
        "ingredients": "Dry Mango (Amchoor), Black Salt, Roasted Cumin, Asafoetida, Mint, Black Pepper, Coriander, Dry Ginger, Ajwain.",
        "how_to_use": "Dust over fruit bowls, fried snacks, sprouted salads, dahi vada, and paneer tikka right before serving.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "Heritage Meat Masala",
        "slug": "heritage-meat-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-MEAT-100G",
        "weight_label": "100 gm",
        "price": Decimal("120.00"),
        "mrp": Decimal("150.00"),
        "short_description": "Robust, slow-roasted spice blend formulated to tenderize and infuse deep aroma into mutton and chicken curries.",
        "description": "<p>A royal secret blend formulated for rich, slow-cooked meat gravies. Heavy on warming spices like black cardamom, star anise, cloves, and black pepper that naturally tenderize cuts of mutton, chicken, and lamb while infusing every fiber with hearty roasted aroma.</p>",
        "ingredients": "Coriander, Cumin, Black Pepper, Black Cardamom, Cloves, Cinnamon, Star Anise, Bay Leaves, Fennel, Garlic, Onion, Degi Mirch.",
        "how_to_use": "Marinate meat with yogurt, ginger-garlic paste, and 2 tsp Meat Masala. Slow-cook on low flame for tender richness.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Refreshing Raita Masala",
        "slug": "refreshing-raita-masala",
        "category_slug": "chaat-drinks-refreshers",
        "sku": "MM-RMM-RAIT-100G",
        "weight_label": "100 gm",
        "price": Decimal("100.00"),
        "mrp": Decimal("130.00"),
        "short_description": "Cooling digestive blend of bhuna jeera, black salt, and mint powder that turns plain curd into a feast.",
        "description": "<p>A soothing, aromatic seasoning specially balanced for curd and yogurt preparations. Features freshly roasted cumin (bhuna jeera), cooling dried mint leaves, and therapeutic black salt to assist gut digestion and elevate boondi raita, cucumber raita, and chaas.</p>",
        "ingredients": "Roasted Cumin (Bhuna Jeera), Black Salt, Dried Mint Leaves, Black Pepper, Pomegranate Seed, Asafoetida, Rock Salt.",
        "how_to_use": "Whisk 1/2 tsp into 1 cup of fresh chilled dahi with boondi or cucumber, and garnish with fresh coriander.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Authentic Sambhar Masala",
        "slug": "authentic-sambhar-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-SAMB-100G",
        "weight_label": "100 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "Traditional South Indian blend of slow-roasted lentils and spices for fragrant Udupi-style sambhar.",
        "description": "<p>Crafted following time-tested Udupi recipes. Made by slow-roasting chana dal, urad dal, whole red chillies, coriander seeds, and curry leaves before stone-grinding. Imparts that heavenly fragrant aroma and body to piping hot dal and vegetable sambhar.</p>",
        "ingredients": "Coriander, Chana Dal, Urad Dal, Guntur Red Chillies, Cumin, Fenugreek (Methi), Asafoetida, Curry Leaves, Turmeric.",
        "how_to_use": "Add 2 teaspoons to boiled toor dal and seasonal vegetables with tamarind pulp, and boil for 5 minutes before tadka.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Chowpatty Pav Bhaji Masala",
        "slug": "chowpatty-pav-bhaji-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-PAVB-100G",
        "weight_label": "100 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "Iconic Mumbai-style spice blend providing butter-infused aroma, bright color, and tangy zest to mashed bhaji.",
        "description": "<p>Bring the magical aroma of Mumbai's street stalls directly to your kitchen. High in aromatic Kashmiri chilli for vivid red hue, complemented by tangy amchoor, fennel, and stone-ground coriander. Blends smoothly with butter to make lip-smacking pav bhaji.</p>",
        "ingredients": "Kashmiri Red Chilli, Coriander, Cumin, Amchoor, Fennel, Green Cardamom, Cinnamon, Cloves, Black Pepper, Star Anise.",
        "how_to_use": "Add 2 tbsp to mashed boiled vegetables and butter on a large tawa, cooking until bubbling and fragrant.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "Dhaba Daal Fry Masala",
        "slug": "dhaba-daal-fry-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-DAAL-100G",
        "weight_label": "100 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "Robust highway-dhaba style tempering mix with garlic, tomato, and kasuri methi for everyday dals.",
        "description": "<p>Turn simple yellow dal into a comforting masterpiece. This Dhaba Daal Fry Masala brings together roasted cumin, dried garlic, tomato essence, mild Kashmiri chilli, and kasuri methi to recreate that smokey, buttery dhaba tadka right on your stove.</p>",
        "ingredients": "Cumin, Coriander, Dehydrated Garlic, Ginger, Tomato Powder, Kashmiri Chilli, Turmeric, Asafoetida, Kasuri Methi.",
        "how_to_use": "Fry 1.5 tsp in 2 tbsp ghee with chopped onions, then pour the sizzling tadka over cooked toor or moong dal.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Homestyle Sabji Masala",
        "slug": "homestyle-sabji-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-SABJ-100G",
        "weight_label": "100 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "The dependable everyday seasoning that makes seasonal dry vegetables and curries flavorful and appetizing.",
        "description": "<p>The secret weapon of everyday Indian home cooking. Specially balanced with whole stone-ground coriander, cumin, dry mango, and warm spices. Perfectly accents dry bhindi, aloo gobhi, baingan bharta, and tinda without overpowering the natural vegetable sweetness.</p>",
        "ingredients": "Coriander Seeds, Cumin, Turmeric, Dry Mango, Black Pepper, Red Chilli, Ginger, Nutmeg, Bay Leaf.",
        "how_to_use": "Sprinkle 1 tsp over chopped sautéed vegetables during the last 5 minutes of cooking and stir gently.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Pahari Rajma Masala",
        "slug": "pahari-rajma-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-RAJM-100G",
        "weight_label": "100 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "Hearty slow-cooked kidney bean spice blend with black cardamom, anardana, and mace for thick creamy gravy.",
        "description": "<p>Inspired by the traditional Jammu and Kashmiri hill stations, this Rajma Masala combines black cardamom, wild anardana, dry ginger, and mace to tenderize kidney beans and yield that iconic velvety, aromatic, spiced gravy perfect over steamed chawal.</p>",
        "ingredients": "Coriander, Pomegranate Seeds (Anardana), Cumin, Black Cardamom, Cinnamon, Kashmiri Chilli, Dry Ginger, Mace.",
        "how_to_use": "Simmer 2 teaspoons with pressure-cooked rajma and onion-tomato gravy for 15-20 minutes on gentle heat.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Royal Shahi Garam Masala",
        "slug": "royal-shahi-garam-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-GM-100G",
        "weight_label": "100 gm",
        "price": Decimal("180.00"),
        "mrp": Decimal("210.00"),
        "short_description": "100% whole sweet & pungent spices without cheap coriander fillers. Just a pinch fills the home with fragrance.",
        "description": "<p>An uncompromising royal blend crafted exclusively from premium warming whole spices: green cardamom, black cardamom, cloves, cinnamon, mace (javitri), nutmeg, black pepper, and star anise. Zero coriander seed fillers. A half teaspoon at the end of cooking unlocks an intoxicating feast of aroma.</p>",
        "ingredients": "Royal Cumin, Green Cardamom, Black Cardamom, Cloves, Cinnamon, Mace (Javitri), Nutmeg (Jaiphal), Black Pepper, Star Anise, Bay Leaf.",
        "how_to_use": "Add 1/2 tsp at the very end of cooking, cover with lid for 2 minutes to seal in the volatile aromatic oils.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "Halwai-Style Kachauri Masala",
        "slug": "halwai-style-kachauri-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-KACH-200G",
        "weight_label": "200 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "Coarsely ground fennel, asafoetida, and cumin blend for authentic halwai-style dal kachoris and bedmi puris.",
        "description": "<p>Recreate the sensational crispy dal kachoris of Rajasthan and UP halwais. Specially coarse-ground with sweet saunf, strong hing, coriander, and amchoor. Infuses urad dal and moong dal fillings with mouthwatering aroma and long-lasting shelf freshness.</p>",
        "ingredients": "Fennel (Saunf), Coriander, Cumin, Asafoetida, Red Chilli, Amchoor, Ginger, Black Salt, Garam Masala.",
        "how_to_use": "Mix 2-3 tbsp into soaked ground dal filling for kachoris, or knead into dough for crispy bedmi puris.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "All In One Magic Masala",
        "slug": "all-in-one-magic-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-AIO-125G",
        "weight_label": "125 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "Universal flavor booster that instantly makes noodles, fried rice, sandwiches, eggs, and snacks taste magical.",
        "description": "<p>The ultimate pantry superhero that everyone loves. A secret blend of roasted spices, natural onion, garlic, black pepper, and tangy mango powder that instantly elevates Maggi noodles, fried rice, french fries, omelettes, parathas, and evening snacks with mouthwatering flavor.</p>",
        "ingredients": "Roasted Coriander, Cumin, Garlic, Onion, Black Pepper, Kashmiri Chilli, Turmeric, Amchoor, Cinnamon, Nutmeg.",
        "how_to_use": "Sprinkle over cooked noodles, fried eggs, potato wedges, sandwiches, or dry sabji for an instant flavor explosion.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "Pure Kashmiri Kasoori Methi",
        "slug": "pure-kashmiri-kasoori-methi",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-RMM-KASO-25G",
        "weight_label": "25 gm",
        "price": Decimal("65.00"),
        "mrp": Decimal("95.00"),
        "short_description": "Sun-dried whole Kasur fenugreek leaves with intense herbal aroma and zero dust or bitter stems.",
        "description": "<p>Hand-picked from the revered fenugreek fields of Kasur and slowly sun-dried. Naturally dark green and completely free from bitter thick stems, sand, or dust. When rubbed between palms, it releases that signature rich herbal aroma that defines gourmet North Indian restaurant gravies.</p>",
        "ingredients": "100% Hand-picked, sun-dried Kasuri Fenugreek Leaves (Trigonella foenum-graecum).",
        "how_to_use": "Lightly roast on a dry tawa for 10 seconds, crush between palms, and sprinkle over butter chicken, paneer, and dals.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Traditional Kashmiri Masala (Wazwan Blend)",
        "slug": "traditional-kashmiri-masala-wazwan-blend",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-KASH-100G",
        "weight_label": "100 gm",
        "price": Decimal("130.00"),
        "mrp": Decimal("160.00"),
        "short_description": "Authentic Himalayan recipe with dry ginger (sonth), fennel (saunf), and Kashmiri chillies for royal curries.",
        "description": "<p>Formulated according to the royal culinary traditions of Kashmir's Wazwan chefs. Built on a delicate foundation of dry ginger (sonth), fragrant sweet fennel (saunf), mild Kashmiri chillies, and black cardamom. Delivers that iconic fragrant red gravy for Dum Aloo, Nadru, and Rogan Josh without harsh heat.</p>",
        "ingredients": "Kashmiri Degi Mirch, Fennel Powder (Saunf), Dry Ginger (Sonth), Black Cardamom, Cinnamon, Cloves, Asafoetida.",
        "how_to_use": "Whisk 2 tsp in yogurt or water before adding to pan for authentic Kashmiri dum cooking.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Aroma-Lock Shahi Paneer Masala",
        "slug": "aroma-lock-shahi-paneer-masala",
        "category_slug": "ready-masala-blends",
        "sku": "MM-RMM-SHAHI-100G",
        "weight_label": "100 gm",
        "price": Decimal("140.00"),
        "mrp": Decimal("170.00"),
        "short_description": "Regal blend with green cardamom, mace, and cashews for velvety, sweet-savory Mughlai paneer gravies.",
        "description": "<p>Crafted for creating luxurious, velvety paneer curries worthy of royalty. Blended with fragrant green cardamom, sweet mace (javitri), melon seed powder, and mild spices that harmonize effortlessly with butter, cream, and fresh malai paneer cubes.</p>",
        "ingredients": "Cashew Nut Powder, Melon Seeds, Green Cardamom, Coriander, Cumin, Kashmiri Chilli, Mace, Nutmeg, Fenugreek, Cinnamon.",
        "how_to_use": "Cook 2 teaspoons in tomato-cashew puree with butter, add paneer cubes, and finish with fresh cream.",
        "is_featured": True,
        "is_bestseller": True,
    },

    # ── Spice Powders & Whole Spices ──
    {
        "name": "Cooling Jaljeera Masala",
        "slug": "cooling-jaljeera-masala",
        "category_slug": "chaat-drinks-refreshers",
        "sku": "MM-SPW-JALJ-125G",
        "weight_label": "125 gm",
        "price": Decimal("80.00"),
        "mrp": Decimal("110.00"),
        "short_description": "Traditional summer digestive cooler mix with mint, roasted cumin, black salt, and dry mango.",
        "description": "<p>The ultimate Indian summer savior. Our Jaljeera Masala combines cooling mint powder, slow-roasted cumin, rock salt, dry mango, and digestive ginger. Rehydrates the body, boosts appetite, and soothes digestion on hot afternoons.</p>",
        "ingredients": "Mint Powder, Cumin, Black Salt, Dry Mango, Ginger, Asafoetida, Black Pepper, Citric Acid.",
        "how_to_use": "Mix 1 tbsp in a glass of ice water with fresh lemon juice and crisp boondi.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Old Delhi Shikanji Masala",
        "slug": "old-delhi-shikanji-masala",
        "category_slug": "chaat-drinks-refreshers",
        "sku": "MM-SPW-SHIK-125G",
        "weight_label": "125 gm",
        "price": Decimal("90.00"),
        "mrp": Decimal("120.00"),
        "short_description": "Famous street-style spiced lemonade masala for crafting fizzy, tangy, and digestive fresh lime soda.",
        "description": "<p>Inspired by the legendary shikanji carts of Chandni Chowk. A master formulation of bhuna jeera, black salt, black pepper, and cooling mint that turns simple lemonade or soda into an unforgettable sweet, salty, and tangy refresher.</p>",
        "ingredients": "Roasted Cumin, Black Salt, Black Pepper, Mint, Lemon Extract, Ginger, Rock Salt.",
        "how_to_use": "Squeeze half a lemon into chilled club soda or water, add sugar syrup, and stir in 1/2 tsp Shikanji Masala.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Royal Chai Masala (4 Inch Freshness Pack)",
        "slug": "royal-chai-masala-4-inch-freshness-pack",
        "category_slug": "chaat-drinks-refreshers",
        "sku": "MM-SPW-CHAI-100G",
        "weight_label": "100 gm",
        "price": Decimal("220.00"),
        "mrp": Decimal("250.00"),
        "short_description": "Immunity-boosting tea spice blend packed with green cardamom, ginger, cinnamon, and cloves in a 4-inch jar.",
        "description": "<p>Turn your daily morning tea into a royal ritual. Packed in a sealed 4-inch freshness container to preserve volatile essential oils. Handcrafted with high-grade green cardamom, Ceylon cinnamon, cloves, sun-dried ginger, and nutmeg. Warms the chest, lifts fatigue, and strengthens immunity.</p>",
        "ingredients": "Green Cardamom (Elaichi), Ceylon Cinnamon (Dalchini), Clove (Laung), Dry Ginger (Sonth), Black Pepper (Kali Mirch), Nutmeg (Jaiphal).",
        "how_to_use": "Add a generous pinch (1/4 tsp per cup) while boiling milk and tea leaves. Let it steep for 1 minute before straining.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "South Indian Gun Powder (Idli Podi)",
        "slug": "south-indian-gun-powder-idli-podi",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-SPW-GUNP-100G",
        "weight_label": "100 gm",
        "price": Decimal("130.00"),
        "mrp": Decimal("160.00"),
        "short_description": "Crispy, spicy roasted lentil and red chilli podi. Mix with hot ghee or sesame oil for idlis and dosas.",
        "description": "<p>Authentic Tamil Nadu style Milagai Podi, popularly known as Gun Powder. Roasted urad dal, chana dal, fiery Guntur chillies, and nutty sesame seeds stone-ground into a coarse, crunchy condiment. The quintessential companion to steaming hot idlis and crisp ghee dosas.</p>",
        "ingredients": "Roasted Urad Dal, Chana Dal, Guntur Red Chillies, Sesame Seeds (Til), Curry Leaves, Asafoetida, Salt.",
        "how_to_use": "Spoon 1-2 tbsp into a bowl, pour hot melted desi ghee or cold-pressed sesame oil over it, and dip idli/dosa.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Sweet Lucknowi Green Saunf (Fennel)",
        "slug": "sweet-lucknowi-green-saunf-fennel",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-SPW-SAUN-100G",
        "weight_label": "100 gm",
        "price": Decimal("90.00"),
        "mrp": Decimal("120.00"),
        "short_description": "Hand-cleaned tender green fennel seeds with natural licorice sweetness for mukhwas and aromatic cooking.",
        "description": "<p>Directly harvested from the fertile plains of Lucknow. These whole green fennel seeds are naturally sweet, plump, and deeply aromatic. Enjoy as an after-meal digestive mouth freshener (mukhwas) or use in tadka for pickles, curries, and confectionery.</p>",
        "ingredients": "100% Hand-cleaned, pesticide-free Green Fennel Seeds (Foeniculum vulgare).",
        "how_to_use": "Chew 1/2 tsp after meals for digestive freshness, or lightly crush into gravies and dough.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Sun-Dried Ginger Powder (Sonth)",
        "slug": "sun-dried-ginger-powder-sonth",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-SPW-GING-100G",
        "weight_label": "100 gm",
        "price": Decimal("100.00"),
        "mrp": Decimal("130.00"),
        "short_description": "100% pure dried ginger root powder offering sharp warmth and therapeutic digestive benefits.",
        "description": "<p>Stone-ground from premium cured dry ginger roots (sonth). Offers a clean, pungent heat with zesty undertones. An indispensable Ayurvedic staple for soothing throat remedies, warming winter herbal teas, gingerbread baking, and festive sweet and sour saunth chutneys.</p>",
        "ingredients": "100% Pure Sun-Dried Ginger Rhizomes (Zingiber officinale).",
        "how_to_use": "Add 1/2 tsp to herbal kadhas, tea, sweet tamarind chutney, or winter laddoos.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Tangy Amchoor Powder (Dry Mango)",
        "slug": "tangy-amchoor-powder-dry-mango",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-SPW-AMCH-100G",
        "weight_label": "100 gm",
        "price": Decimal("75.00"),
        "mrp": Decimal("105.00"),
        "short_description": "Stone-ground sun-dried raw green mangoes for clean, moisture-free sourness in dry vegetables and snacks.",
        "description": "<p>Harvested from young green mangoes, sliced, and sun-dried to perfection before cold stone-grinding. Imparts an authentic fruity sourness to stuffed parathas, samosa fillings, dry bhindi, and curries without adding unwanted liquid moisture.</p>",
        "ingredients": "100% Pure Sun-Dried Raw Green Mango.",
        "how_to_use": "Add 1/2 to 1 tsp towards the end of cooking dry vegetable dishes or paratha stuffings.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Tellicherry Black Pepper Powder (4 Inch Pack)",
        "slug": "tellicherry-black-pepper-powder-4-inch-pack",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-SPW-BPEP-100G",
        "weight_label": "100 gm",
        "price": Decimal("220.00"),
        "mrp": Decimal("250.00"),
        "short_description": "Bold Malabar black peppercorns freshly ground and packed in a 4-inch freshness container.",
        "description": "<p>Revered worldwide as the king of spices. Our black pepper is sourced from Kerala's lush Malabar coast, selected for its bold size and rich piperine oil content. Stone-ground into fine aromatic powder and sealed in a 4-inch airtight jar to guarantee sharp heat and woody fragrance in every pinch.</p>",
        "ingredients": "100% Pure Malabar Bold Black Peppercorns (Piper nigrum).",
        "how_to_use": "Dust over morning eggs, hot soups, pasta, steaks, and soothing turmeric latte.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Dakshini Safed Mirch (White Pepper Powder - 4 Inch Pack)",
        "slug": "dakshini-safed-mirch-white-pepper-powder-4-inch-pack",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-SPW-WMIR-100G",
        "weight_label": "100 gm",
        "price": Decimal("340.00"),
        "mrp": Decimal("370.00"),
        "short_description": "Prized de-husked white peppercorns ground into velvety powder in a 4-inch jar for clean heat and eye health.",
        "description": "<p>A precious culinary spice known as Dakshini Mirch or Safed Mirch. Prepared by de-husking fully ripe peppercorns to isolate the inner seed. Provides a sharp, clean fiery kick and therapeutic eye-health benefits without altering the pristine white color of creamy kormas, soups, and Continental dishes.</p>",
        "ingredients": "100% Pure Dehusked White Peppercorns (Safed Mirch).",
        "how_to_use": "Use in white sauce pasta, creamy paneer gravies, mushroom soup, and potato salads.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Pure Garden Mint Powder (Pudina)",
        "slug": "pure-garden-mint-powder-pudina",
        "category_slug": "herbs-salts-seasonings",
        "sku": "MM-SPW-MINT-100G",
        "weight_label": "100 gm",
        "price": Decimal("95.00"),
        "mrp": Decimal("125.00"),
        "short_description": "100% farm-fresh mint leaves shade-dried and powdered for instant cooling aroma in marinades and drinks.",
        "description": "<p>Enjoy the crisp, invigorating essence of fresh garden pudina year-round. Harvested at peak potency, gently shade-dried to preserve natural menthol, and powdered. Perfect for biryani garnishing, tandoori marinades, yogurt dips, and instant mint lemonade.</p>",
        "ingredients": "100% Pure Shade-Dried Garden Mint Leaves (Mentha arvensis).",
        "how_to_use": "Mix into curd for instant mint raita, or add to kebab marinades and herbal teas.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Ceylon Dalchini Powder (Cinnamon - 4 Inch Pack)",
        "slug": "ceylon-dalchini-powder-cinnamon-4-inch-pack",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-SPW-DALC-100G",
        "weight_label": "100 gm",
        "price": Decimal("190.00"),
        "mrp": Decimal("220.00"),
        "short_description": "Sweet, fragrant cinnamon bark finely ground and protected in a 4-inch freshness jar.",
        "description": "<p>Stone-ground from delicate inner bark layers of high-grade cinnamon. Rich in natural cinnamaldehyde and polyphenols with sweet woody warmth. Sealed in a 4-inch container to keep volatile sweet oils intact for desserts, curries, morning oats, and coffee.</p>",
        "ingredients": "100% Pure Stone-Ground Cinnamon Bark (Cinnamomum verum).",
        "how_to_use": "Stir 1/4 tsp into warm water with honey, sprinkle over oatmeal or coffee, or add to biryani gravy.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Roasted Jeera Powder (Cumin - 4 Inch Pack)",
        "slug": "roasted-jeera-powder-cumin-4-inch-pack",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-SPW-JEER-100G",
        "weight_label": "100 gm",
        "price": Decimal("110.00"),
        "mrp": Decimal("140.00"),
        "short_description": "Slow-roasted cumin seeds stone-ground into nutty, deeply aromatic powder in a 4-inch jar.",
        "description": "<p>Whole cumin seeds gently roasted on iron tawas until deeply fragrant, then cold stone-ground into aromatic brown powder. Packed in a 4-inch jar to preserve its intense earthy nuttiness. Elevates dal tadka, buttermilk, chaats, and curries with unforgettable aroma.</p>",
        "ingredients": "100% Whole Roasted Cumin Seeds (Cuminum cyminum).",
        "how_to_use": "Sprinkle over buttermilk, raitas, fruit chaat, or stir into curries and dals.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "Cold Stone-Ground Haldi (Turmeric - 6 Inch Pack)",
        "slug": "cold-stone-ground-haldi-turmeric-6-inch-pack",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-SPW-HALD",
        "weight_label": "125 gm",
        "price": Decimal("120.00"),
        "mrp": Decimal("150.00"),
        "short_description": "High-curcumin Salem turmeric rhizomes stone-ground at low RPM for maximum medicinal purity and color.",
        "description": "<p>Experience the pure therapeutic brilliance of nature's miracle spice. Sourced directly from premier Salem turmeric rhizomes with tested high-curcumin levels. Cold stone-ground at low RPM to ensure essential oils and anti-inflammatory properties are never lost to frictional heat. Zero chemical polish, additives, or lead chromate.</p>",
        "ingredients": "100% Pure High-Curcumin Turmeric Rhizomes (Curcuma longa).",
        "how_to_use": "Add 1/2 tsp to daily curries and dals, or stir into warm milk with black pepper for golden wellness milk.",
        "is_featured": True,
        "is_bestseller": True,
        "variants": [
            {"size_label": "125 gm", "price": Decimal("120.00"), "mrp": Decimal("150.00"), "sku": "MM-SPW-HALD-125G"},
            {"size_label": "200 gm", "price": Decimal("135.00"), "mrp": Decimal("165.00"), "sku": "MM-SPW-HALD-200G"}
        ]
    },
    {
        "name": "Cold Stone-Ground Dhaniya (Coriander - 6 Inch Pack)",
        "slug": "cold-stone-ground-dhaniya-coriander-6-inch-pack",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-SPW-DHAN",
        "weight_label": "125 gm",
        "price": Decimal("120.00"),
        "mrp": Decimal("150.00"),
        "short_description": "Green Rajasthan coriander seeds cold-milled to create thick, citrusy, and aromatic curry gravies.",
        "description": "<p>The aromatic anchor of authentic Indian cuisine. Selected from fresh, green Rajasthani coriander seeds celebrated for high linalool essential oil content. Stone-ground at cool temperatures to deliver refreshing citrus notes and hearty natural thickening to gravies, dals, and marinades.</p>",
        "ingredients": "100% Pure Stone-Ground Coriander Seeds (Coriandrum sativum).",
        "how_to_use": "Add 1 to 2 tsp with turmeric and chilli powder while sautéing onions and tomatoes for curry base.",
        "is_featured": True,
        "is_bestseller": True,
        "variants": [
            {"size_label": "125 gm", "price": Decimal("120.00"), "mrp": Decimal("150.00"), "sku": "MM-SPW-DHAN-125G"},
            {"size_label": "200 gm", "price": Decimal("135.00"), "mrp": Decimal("165.00"), "sku": "MM-SPW-DHAN-200G"}
        ]
    },
    {
        "name": "Cold Stone-Ground Lal Mirch (Red Chilli - 6 Inch Pack)",
        "slug": "cold-stone-ground-lal-mirch-red-chilli-6-inch-pack",
        "category_slug": "daily-cooking-pure-spices",
        "sku": "MM-SPW-MIRC",
        "weight_label": "125 gm",
        "price": Decimal("155.00"),
        "mrp": Decimal("185.00"),
        "short_description": "Hand-stemmed whole red chillies stone-ground for balanced pungent heat and rich crimson color.",
        "description": "<p>A master blend of fiery Byadgi and Guntur red chillies, stem-plucked by hand and cold-ground without mineral oils or artificial red dyes. Delivers radiant natural red color to gravies with a clean, building heat that delights spice lovers without harsh irritation.</p>",
        "ingredients": "100% Pure Sun-Dried Stemless Red Chillies (Capsicum annuum).",
        "how_to_use": "Add 1/2 to 1 tsp to oil during tempering or in curry base according to your desired heat level.",
        "is_featured": True,
        "is_bestseller": True,
        "variants": [
            {"size_label": "125 gm", "price": Decimal("155.00"), "mrp": Decimal("185.00"), "sku": "MM-SPW-MIRC-125G"},
            {"size_label": "200 gm", "price": Decimal("185.00"), "mrp": Decimal("215.00"), "sku": "MM-SPW-MIRC-200G"}
        ]
    },

    # ── Handcrafted Achaar (Pickles - 6 Inch Jars) ──
    {
        "name": "Traditional Aam Ka Achaar (Mango Pickle - 6 Inch Jar)",
        "slug": "traditional-aam-ka-achaar-mango-pickle-6-inch-jar",
        "category_slug": "handcrafted-achaar",
        "sku": "MM-ACH-AAM-200G",
        "weight_label": "200 gm",
        "price": Decimal("95.00"),
        "mrp": Decimal("125.00"),
        "short_description": "Sun-matured raw Ramkela mango pickle cured in pure kachi ghani mustard oil with whole heirloom spices.",
        "description": "<p>Prepared using Grandma's time-tested heirloom recipe. Crisp raw green Ramkela mangoes cut and marinated with coarse-ground fenugreek seeds, fennel, kalonji, mustard, and fragrant hing in cold-pressed mustard oil. Matured naturally under warm sunshine in traditional clay martabans.</p>",
        "ingredients": "Raw Mangoes, Cold-Pressed Mustard Oil, Fenugreek (Methi), Fennel (Saunf), Nigella (Kalonji), Turmeric, Red Chilli, Salt, Asafoetida.",
        "how_to_use": "Serve alongside hot stuffed parathas, dal chawal, khichdi, and pooris for irresistible home-style comfort.",
        "is_featured": True,
        "is_bestseller": True,
    },
    {
        "name": "Artisanal Mirch Ka Achaar (Chilli Pickle - 6 Inch Jar)",
        "slug": "artisanal-mirch-ka-achaar-chilli-pickle-6-inch-jar",
        "category_slug": "handcrafted-achaar",
        "sku": "MM-ACH-MIRC-200G",
        "weight_label": "200 gm",
        "price": Decimal("120.00"),
        "mrp": Decimal("150.00"),
        "short_description": "Zesty and punchy green & red chilli pickle stuffed with cracked mustard seeds, amchoor, and spices.",
        "description": "<p>For true lovers of pungent spice. Selected firm, crunchy chillies slit and stuffed with stone-ground yellow mustard (rai), dry mango, saunf, and aromatic spices in mustard oil. Delivers a tongue-tingling burst of heat, tang, and crunch with every bite.</p>",
        "ingredients": "Fresh Chillies, Cold-Pressed Mustard Oil, Yellow Mustard (Rai), Saunf, Amchoor, Fenugreek, Turmeric, Salt, Asafoetida.",
        "how_to_use": "Pair a spoonful with poori-bhaji, parathas, or simple curd rice to awaken your meal.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Digestive Nimbu Ka Achaar (Lemon Pickle - 6 Inch Jar)",
        "slug": "digestive-nimbu-ka-achaar-lemon-pickle-6-inch-jar",
        "category_slug": "handcrafted-achaar",
        "sku": "MM-ACH-NIMB-200G",
        "weight_label": "200 gm",
        "price": Decimal("130.00"),
        "mrp": Decimal("160.00"),
        "short_description": "Oil-free traditional sun-ripened Kagzi lemon pickle seasoned with black salt, ajwain, and rock salt.",
        "description": "<p>A classic Ayurvedic digestive treasure. Made with juicy, thin-skinned Kagzi lemons and sun-ripened for weeks until the peel turns tender and translucent. Free from heavy oils; seasoned purely with mineral rock salt, black salt, ajwain, and warming spices to soothe digestion.</p>",
        "ingredients": "Thin-Skinned Kagzi Lemons, Rock Salt, Black Salt, Cumin, Ajwain, Black Pepper, Red Chilli, Asafoetida.",
        "how_to_use": "Enjoy a small piece with everyday lunches, curd rice, or during fasting and recovery meals.",
        "is_featured": False,
        "is_bestseller": False,
    },
    {
        "name": "Gourmet Mix Achaar (Mixed Pickle - 6 Inch Jar)",
        "slug": "gourmet-mix-achaar-mixed-pickle-6-inch-jar",
        "category_slug": "handcrafted-achaar",
        "sku": "MM-ACH-MIXX-200G",
        "weight_label": "200 gm",
        "price": Decimal("95.00"),
        "mrp": Decimal("125.00"),
        "short_description": "Crunchy medley of tender mango, carrot, cauliflower, and lime sun-cured in aromatic mustard oil.",
        "description": "<p>The ultimate North Indian celebration of seasonal produce. A crunchy, savory assortment of raw mango, sweet carrots, crunchy cauliflower florets, green chillies, and tender lime steeped in cold-pressed mustard oil with roasted fenugreek and mustard seeds.</p>",
        "ingredients": "Raw Mango, Carrot, Cauliflower, Green Chilli, Lime, Turnip, Cold-Pressed Mustard Oil, Mixed Whole Spices, Salt.",
        "how_to_use": "The perfect all-rounder accompaniment for everyday roti-sabji, parathas, mathris, and dal chawal.",
        "is_featured": True,
        "is_bestseller": True,
    }
]

print(f"Creating {len(products_data)} distinct products...")

with transaction.atomic():
    for p_info in products_data:
        category = created_categories[p_info["category_slug"]]
        prod = Product.objects.create(
            name=p_info["name"],
            slug=p_info["slug"],
            category=category,
            sku=p_info["sku"],
            short_description=p_info["short_description"],
            description=p_info["description"],
            ingredients=p_info["ingredients"],
            how_to_use=p_info["how_to_use"],
            storage_instructions="Store in a cool, dry place away from direct sunlight. Reseal airtight container or pack after each use.",
            features="100% Pure, Cold Stone Ground, Zero Preservatives, No Artificial Colors or Fillers",
            price=p_info["price"],
            mrp=p_info["mrp"],
            stock_quantity=100,
            is_active=True,
            is_featured=p_info.get("is_featured", False),
            is_bestseller=p_info.get("is_bestseller", False),
            is_customize_combo_eligible=True,
            meta_title=f"{p_info['name']} | Pure Stone-Ground Spices",
            meta_description=p_info["short_description"][:300]
        )
        
        # If variants exist, create them
        if "variants" in p_info:
            for idx, v_info in enumerate(p_info["variants"]):
                ProductVariant.objects.create(
                    product=prod,
                    size_label=v_info["size_label"],
                    price=v_info["price"],
                    mrp=v_info["mrp"],
                    sku=v_info["sku"],
                    stock_quantity=100,
                    is_active=True,
                    display_order=idx
                )
        else:
            # Create a single default variant matching the pack weight
            ProductVariant.objects.create(
                product=prod,
                size_label=p_info["weight_label"],
                price=p_info["price"],
                mrp=p_info["mrp"],
                sku=f"{p_info['sku']}-DEF",
                stock_quantity=100,
                is_active=True,
                display_order=0
            )
            
        print(f"  + Added: {prod.name} ({p_info['weight_label']}) - Price: Rs.{prod.price}, MRP: Rs.{prod.mrp}")

print("\nSuccessfully populated all real products and categories!")
