# Generated by Django 6.1.1 on 2026-09-16 05:06

import apps.core.validators
import ckeditor.fields
import django.db.models.deletion
import imagekit.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=110, unique=True)),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text="Recommended: 600×600 px, JPG/WebP. File is auto-resized on upload.",
                        null=True,
                        upload_to="categories/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("meta_title", models.CharField(blank=True, max_length=160)),
                ("meta_description", models.TextField(blank=True, max_length=320)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=70, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "sku",
                    models.CharField(
                        help_text="Unique product code (e.g. MU-GM-100G).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Full product description — use the rich-text editor.",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description shown on listing cards (max 300 characters).",
                        max_length=300,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Selling price in ₹.", max_digits=10
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum retail price (MRP) shown as a strike-through. Leave blank if no discount.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "main_image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text="Recommended: 1200×1200 px, square, neutral background. File is auto-resized on upload.",
                        null=True,
                        upload_to="products/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                (
                    "main_image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the main image (important for SEO and accessibility).",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show in the Featured section on the homepage.",
                    ),
                ),
                (
                    "is_bestseller",
                    models.BooleanField(
                        default=False,
                        help_text="Show in the Bestsellers row on the homepage.",
                    ),
                ),
                (
                    "is_customize_combo_eligible",
                    models.BooleanField(
                        default=True,
                        help_text="Can this product be selected when building a custom combo?",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("meta_title", models.CharField(blank=True, max_length=160)),
                ("meta_description", models.TextField(blank=True, max_length=320)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="catalog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        help_text="Recommended: 1200×1200 px. Up to 6 gallery images per product. Auto-resized on upload.",
                        upload_to="products/gallery/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Describe what is shown in this image (important for SEO and screen readers).",
                        max_length=200,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size_label",
                    models.CharField(
                        help_text='e.g. "50g", "100g", "500g", "1kg"', max_length=30
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "mrp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("sku", models.CharField(max_length=60, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "size_label"],
                "unique_together": {("product", "size_label")},
            },
        ),
    ]
