# Generated by Django 6.1.1 on 2026-09-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.CharField(
                blank=True,
                default="100% Pure, Cold Stone Ground, Zero Preservatives, No Artificial Colors",
                help_text="Key quality highlights, comma separated.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="how_to_use",
            field=models.TextField(
                blank=True,
                help_text="Usage and recipe instructions, e.g. Add 1 tsp near the end of cooking or in tadka to lock aroma.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(
                blank=True,
                help_text="List of ingredients, e.g. Coriander Seeds, Cumin, Black Pepper, Green Cardamom, Cinnamon, Cloves, Bay Leaf, Ginger.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="storage_instructions",
            field=models.CharField(
                blank=True,
                default="Store in a cool, dry place away from direct sunlight. Reseal airtight zip-lock after every use.",
                help_text="Storage and freshness advice shown in the product accordion.",
                max_length=255,
            ),
        ),
    ]
