# Generated by Django 6.1.1 on 2026-09-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_features_product_how_to_use_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Unique product code (e.g. MU-GM-100G). Auto-generated if left blank.",
                max_length=60,
                unique=True,
            ),
        ),
    ]
