# Generated by Django 6.1.1 on 2026-09-21 07:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Applicable GST rate in percentage (e.g. 5.00 for 5%).",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hsn_code",
            field=models.CharField(
                blank=True,
                default="0910",
                help_text="4-digit HSN/SAC code for GST (e.g. 0910 for Spices/Turmeric, 0904 for Chilli, 0909 for Coriander/Cumin, 2001 for Pickles, 2501 for Salts).",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Selling price in ₹ (inclusive of GST).",
                max_digits=10,
            ),
        ),
    ]
