# Generated by Django 6.1.1 on 2026-09-16 05:06

import apps.core.validators
import ckeditor.fields
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnouncementBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="The text shown in the announcement bar.",
                        max_length=300,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#7C1E1E",
                        help_text="Hex color code, e.g. #7C1E1E",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#FFFFFF",
                        help_text="Hex color code, e.g. #FFFFFF",
                        max_length=7,
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional — makes the whole bar clickable.",
                        max_length=200,
                    ),
                ),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        help_text="Recommended: 1200×400 px. Auto-resized on upload.",
                        upload_to="banners/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                ("link_url", models.CharField(blank=True, max_length=200)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage"),
                            ("category", "Category Pages"),
                            ("checkout", "Checkout"),
                        ],
                        default="homepage",
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                (
                    "featured_image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text="Recommended: 1200×630 px (also used as social share image). Auto-resized on upload.",
                        null=True,
                        upload_to="blog/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                ("featured_image_alt", models.CharField(blank=True, max_length=200)),
                ("content", ckeditor.fields.RichTextField()),
                ("meta_title", models.CharField(blank=True, max_length=160)),
                ("meta_description", models.TextField(blank=True, max_length=320)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to save as draft. Set to publish.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", ckeditor.fields.RichTextField()),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ Item",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "desktop_image",
                    imagekit.models.fields.ProcessedImageField(
                        help_text="Recommended: 1920×800 px, JPG/WebP, under 300KB. Auto-resized on upload.",
                        upload_to="hero/desktop/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                (
                    "mobile_image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text="Recommended: 1080×1350 px (portrait). Auto-resized on upload.",
                        null=True,
                        upload_to="hero/mobile/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        help_text='Button label, e.g. "Shop Now"',
                        max_length=80,
                    ),
                ),
                (
                    "cta_link",
                    models.CharField(
                        blank=True,
                        help_text='URL the button links to, e.g. "/shop/"',
                        max_length=200,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to show immediately when activated.",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to show indefinitely.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        help_text="Full page content. Use the rich-text editor — no HTML knowledge needed."
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=160)),
                ("meta_description", models.TextField(blank=True, max_length=320)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                (
                    "photo",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text="Optional. Recommended: 300×300 px (square), JPG/WebP.",
                        null=True,
                        upload_to="testimonials/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Rating out of 5."
                    ),
                ),
                ("text", models.TextField(help_text="The customer's review text.")),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
