# Generated by Django 6.1.1 on 2026-09-17 11:49

import apps.core.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfluencerReel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "influencer_name",
                    models.CharField(
                        help_text="Full name of the influencer, e.g. Priya Sharma",
                        max_length=100,
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        blank=True,
                        help_text="Social handle, e.g. @priyafoodie",
                        max_length=100,
                    ),
                ),
                (
                    "thumbnail",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text="Cover image for the reel (shown before video plays). Recommended: 600×800 px portrait.",
                        null=True,
                        upload_to="influencer_reels/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                (
                    "embed_url",
                    models.URLField(
                        help_text="Paste the embed URL of the YouTube Short or Instagram Reel. For YouTube: use https://www.youtube.com/embed/VIDEO_ID. For Instagram: use https://www.instagram.com/reel/CODE/embed/."
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Short caption shown on the card, e.g. 'This masala changed my biryani game!'",
                        max_length=200,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("other", "Other"),
                        ],
                        default="youtube",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Influencer Reel",
                "verbose_name_plural": "Influencer Reels",
                "ordering": ["display_order"],
            },
        ),
    ]
