# Generated by Django 6.1.1 on 2026-09-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_influencer_reel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heroslide",
            options={"ordering": ["placement", "display_order"]},
        ),
        migrations.AddField(
            model_name="heroslide",
            name="placement",
            field=models.CharField(
                choices=[
                    ("home", "Homepage"),
                    ("combos", "Combos Page"),
                    ("build_combo", "Build Your Own Combo Page"),
                ],
                default="home",
                help_text="Choose which page this hero slide will appear on.",
                max_length=20,
            ),
        ),
    ]
