# Generated by Django 6.1.1 on 2026-09-18 19:40

import apps.core.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_alter_heroslide_options_heroslide_placement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="influencerreel",
            name="embed_url",
            field=models.URLField(
                help_text="Paste ANY Instagram Reel link (e.g. https://www.instagram.com/reel/C8.../) or YouTube Short / Video link (e.g. https://youtube.com/shorts/...). Auto-converted to embed format on save.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="influencerreel",
            name="influencer_name",
            field=models.CharField(
                help_text="Full name of the creator/influencer, e.g. Priya Sharma",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="influencerreel",
            name="platform",
            field=models.CharField(
                choices=[
                    ("youtube", "YouTube"),
                    ("instagram", "Instagram"),
                    ("other", "Other"),
                ],
                default="youtube",
                help_text="Auto-detected from URL, or select manually.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="influencerreel",
            name="thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                help_text="Optional cover image for the reel. Recommended: 600×800 px portrait.",
                null=True,
                upload_to="influencer_reels/",
                validators=[
                    apps.core.validators.FileSizeValidator(max_mb=10),
                    apps.core.validators.ImageTypeValidator(),
                ],
            ),
        ),
    ]
