# Generated by Django 6.1.1 on 2026-09-18 20:11

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_alter_influencerreel_embed_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencerreel",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Optional: Upload an MP4 video directly (recommended for 100% reliable mobile playback without third-party iframe blocks).",
                null=True,
                upload_to="influencer_reels/videos/",
                validators=[apps.core.validators.FileSizeValidator(max_mb=50)],
            ),
        ),
        migrations.AlterField(
            model_name="influencerreel",
            name="embed_url",
            field=models.URLField(
                blank=True,
                help_text="Paste ANY Instagram Reel link (e.g. https://www.instagram.com/reel/C8.../) or YouTube Short / Video link (e.g. https://youtube.com/shorts/...). Auto-converted to embed format on save.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="influencerreel",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("video", "Direct Video (MP4)"),
                    ("other", "Other"),
                ],
                default="instagram",
                help_text="Auto-detected from URL, or select manually.",
                max_length=20,
            ),
        ),
    ]
