# Generated by Django 6.1.1 on 2026-09-19 07:19

import apps.core.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_influencerreel_video_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslide",
            name="show_text_overlay",
            field=models.BooleanField(
                default=True,
                help_text="Show text overlay, subtitle, and CTA button over the image. Uncheck this if your uploaded banner graphic already has text designed on it.",
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="cta_link",
            field=models.CharField(
                blank=True,
                help_text='URL the button or entire banner links to, e.g. "/combos/build/"',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="desktop_image",
            field=imagekit.models.fields.ProcessedImageField(
                help_text="Recommended: 1920×800 px (ratio 2.4:1), JPG/WebP. The banner container scales smoothly with zero distortion.",
                upload_to="hero/desktop/",
                validators=[
                    apps.core.validators.FileSizeValidator(max_mb=10),
                    apps.core.validators.ImageTypeValidator(),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="mobile_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                help_text="Recommended: 1080×1350 px (4:5 portrait) or 1080×1080 px (1:1 square). Auto-scaled on mobile.",
                null=True,
                upload_to="hero/mobile/",
                validators=[
                    apps.core.validators.FileSizeValidator(max_mb=10),
                    apps.core.validators.ImageTypeValidator(),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Slide heading. Leave blank or uncheck 'show text overlay' if your image already has text.",
                max_length=200,
            ),
        ),
    ]
