# Generated by Django 6.1.1 on 2026-09-19 08:06

import apps.core.validators
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_heroslide_show_text_overlay_alter_heroslide_cta_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="desktop_image",
            field=imagekit.models.fields.ProcessedImageField(
                help_text="Desktop Banner Size: 1920 × 500 px. Sleek, professional full-width banner format.",
                upload_to="hero/desktop/",
                validators=[
                    apps.core.validators.FileSizeValidator(max_mb=10),
                    apps.core.validators.ImageTypeValidator(),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="mobile_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                help_text="Mobile Banner Size: 1080 × 600 px. Compact mobile banner format.",
                null=True,
                upload_to="hero/mobile/",
                validators=[
                    apps.core.validators.FileSizeValidator(max_mb=10),
                    apps.core.validators.ImageTypeValidator(),
                ],
            ),
        ),
    ]
