# Generated by Django 6.1.1 on 2026-09-21 09:35

import apps.core.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_alter_heroslide_desktop_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageAssemblySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_image",
                    imagekit.models.fields.ProcessedImageField(
                        help_text="Assembly Section Hero Image (Final Reveal Card). Recommended size: 1200 × 675 px (16:9 ratio). This image is shown inside the dark combo reveal card when the user finishes scrolling through the assembly section.",
                        upload_to="assembly/",
                        validators=[
                            apps.core.validators.FileSizeValidator(max_mb=10),
                            apps.core.validators.ImageTypeValidator(),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide the custom image and use the default assembled pack photo.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Homepage Assembly Section",
                "verbose_name_plural": "Homepage Assembly Section",
            },
        ),
    ]
