# Generated by Django 6.1.1 on 2026-09-21 11:55

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo with the review.",
                null=True,
                upload_to="reviews/",
                validators=[
                    apps.core.validators.FileSizeValidator(max_mb=10),
                    apps.core.validators.ImageTypeValidator(),
                ],
            ),
        ),
    ]
